### ISSUE TITLE
Just discovered Cloud-vSwitch and will post a few questions

### ISSUE THREAD

**Issue by bmullan** [BU-NU-CLOUD-SP16/Cloud-vSwitch#1]
Is there any development still occurring?   If so might there be the possibility of changing VPN from OpenVPN to WireGuard?

Reason I ask is contained in the following White Paper from a Research Team at the University of Gent which tested OpenVPN, WIreGuard, ZeroTier, SoftEther and TINC.    

The results were very interesting but may show why I ask about the possibility of changing from OpenVPN to WireGuard.

thanks
Brian Mullan
Raleigh, North Carolina USA

[Scalability Testing Results - Mesh VPN technologies.pdf](https://github.com/BU-NU-CLOUD-SP16/Cloud-vSwitch/files/3929590/Scalability.Testing.Results.-.Mesh.VPN.technologies.pdf)

**Comment by bmullan** [comment]
My own use-case for a VPN environment...

I retired from 20 Years at Cisco Systems in 2014.   I now spend my time trying to help Schools with technology related issues.

I focus on Ubuntu Linux and **[LXD Containers](https://linuxcontainers.org/lxd/introduction/)**.

LXD containers are termed "system" containers because they run a complete Linux distro in each container (fedora, CentOS, Debian, Ubuntu, Alpine, Oracle  etc) -vs- Docker containers that are called "process" or "application" containers.

One of my projects is here:  **https://github.com/bmullan/ciab-remote-desktop**

However, my research over the last 6 months has been into finding a "best" solution for multi-tenant, multi-node/server/host, multi-cloud/hybrid secure networking that would support something like the following diagram.

Clicking on the diagram should enlarge it for you...


![CIAB Overview Diagram (generic)](https://user-images.githubusercontent.com/1682855/70283558-98d3c900-178f-11ea-8e55-df65db3f8146.png)

**Comment by shuwens** [comment]
Hi brian,

This is only a class project so we have ceased the development a while back. You are welcome to fork the repo or make any changes etc. I will be happy to help if licensing is an issue.

**Comment by bmullan** [comment]
Your team did a great job on Cloud vSwitch and the GUI mgmt tool.
I was impressed :-)
